### ISSUE TITLE
AttributeError: module 'shlex' has no attribute 'join'

### ISSUE THREAD

**Issue by justin-stephenson** [cockpit-project/bots#3220]
Hi,

In [cockpit-session-recording](https://github.com/Scribery/cockpit-session-recording) our CI runs are failing with logs similar to the following (https://cockpit-session-recording.semaphoreci.com/jobs/24de81b3-6deb-46c3-bd3d-85a065ed0f95/plain_logs.txt)

It seems python 3.8 is needed, but I'm not sure how to handle this in our CI environment. Could you please suggest what is the proper way to fix this? Our CI configuration looks like https://raw.githubusercontent.com/Scribery/cockpit-session-recording/main/.semaphore/semaphore.yml

~~~
# testDisplayDrag (__main__.TestApplication) 00:00
Traceback (most recent call last): 00:00
  File "test/common/testlib.py", line 852, in setUp 00:00
    machine.start() 00:00
  File "/home/semaphore/cockpit-session-recording/cockpit-session-recording/bots/machine/machine_core/machine_virtual.py", line 432, in start 00:00
    self._start_qemu() 00:00
  File "/home/semaphore/cockpit-session-recording/cockpit-session-recording/bots/machine/machine_core/machine_virtual.py", line 325, in _start_qemu 00:00
    self.message(shlex.join(cmd)) 00:00
AttributeError: module 'shlex' has no attribute 'join' 00:00
# Result testDisplayDrag (__main__.TestApplication) failed 00:00
# ---------------------------------------------------------------------- 00:00


# testFastforwardControls (__main__.TestApplication) 00:00
Traceback (most recent call last): 00:00
  File "test/common/testlib.py", line 852, in setUp 00:00
    machine.start() 00:00
  File "/home/semaphore/cockpit-session-recording/cockpit-session-recording/bots/machine/machine_core/machine_virtual.py", line 432, in start 00:00
    self._start_qemu() 00:00
  File "/home/semaphore/cockpit-session-recording/cockpit-session-recording/bots/machine/machine_core/machine_virtual.py", line 325, in _start_qemu 00:00
    self.message(shlex.join(cmd)) 00:00
AttributeError: module 'shlex' has no attribute 'join'
~~~

**Comment by martinpitt** [comment]
Hello @justin-stephenson !

Would it be an option for you to just update to `os_image: ubuntu2004`? If not, then we need to find a reimplementation of `shlex.join()` for an older Python. But we know that our CI stuff works on Ubuntu 20.04, we use it on both  CirrusCI and GitHub actions.

Also, I recommend to merge your image-customize calls into one. Each individual call has to boot and shutdown the VM, and that's just a waste of time. You can  have arbitrarily many `-u`, `-r` etc. options, they will be executed in the given order, and none of them require a reboot. Much quicker!

**Comment by justin-stephenson** [comment]
> Hello @justin-stephenson !
> 
> Would it be an option for you to just update to `os_image: ubuntu2004`? If not, then we need to find a reimplementation of `shlex.join()` for an older Python. But we know that our CI stuff works on Ubuntu 20.04, we use it on both CirrusCI and GitHub actions.

Thank you, we will update to ubuntu 20.04, I must have been looking at old semaphore CI documentation as I had checked this initially but missed that 20.04 is a valid os.
> 
> Also, I recommend to merge your image-customize calls into one. Each individual call has to boot and shutdown the VM, and that's just a waste of time. You can have arbitrarily many `-u`, `-r` etc. options, they will be executed in the given order, and none of them require a reboot. Much quicker!

Great, makes sense - thanks very much!
